### ISSUE TITLE
Add bitshift operators

### ISSUE THREAD

**Issue by polwel** [Pharap/FixedPointsArduino#61]
I was surprises to see that shift operations are apparently missing.

```C
#include <FixedPoints.h>
#include <FixedPointsCommon.h>

void setup()
{
  SQ15x16 a = 1;
  a >>= 5;
}

void loop()
{
}
```
The above fails to compile with the following message:
```

FixedPointCalculations:7:5: error: no match for 'operator>>=' (operand types are 'SQ15x16 {aka SFixed<15u, 16u>}' and 'int')

   a >>= 5;
     ^

no match for 'operator>>=' (operand types are 'SQ15x16 {aka SFixed<15u, 16u>}' and 'int')
```

I am using version 1.0.7

**Comment by Pharap** [comment]
Part of the reason they aren't currently defined is because they aren't defined for floating points.

What would you expect the shift operations to do?
What would you use them for?

**Comment by polwel** [comment]
Basically when converting a sensor value (which I retrieve as a word, basically it's some sort of int) to a fixed point representing the logical value in reasonable units. I happen to face a case where this conversion is just a shift operation.

I expect the shift operation to perform to perform a multiplication (or division) by a power of two. Unlike for floats, it is very efficient for fixed points.

**Comment by Pharap** [comment]
Using division would give you the same result for now.

I expect the compiler would convert the division into a shift, though I haven't checked.
If I can find the time I'll check to see if providing shift operators would result in reduced memory consumption or performance improvement.

One of the reasons I'm reluctant is that I want to discourage people from trying to use a bitshift operation as a means of division by a power of two because I feel that using arithmetic operations expresses the intent better.
I.e. the intent is to divide by 32, so `/ 32` expresses that intent better than `>> 5`

---

That said, the internal representation of any fixed point type can be retreived with the `getInternal` member function, and a fixed point type can be constructed from the internal representation with the `fromInternal` _static_ member function.

I.e. the following is possible:
```cpp
#include <FixedPoints.h>
#include <FixedPointsCommon.h>

void setup()
{
  SQ15x16 a = 1;
  auto internal = a.getInternal();
  internal >>= 5;
  a = SQ15x16::fromInternal(internal);
}

void loop()
{
}
```
Or simply:
```cpp
#include <FixedPoints.h>
#include <FixedPointsCommon.h>

void setup()
{
  SQ15x16 a = 1;
  a = SQ15x16::fromInternal(a.getInternal(); >> 5);
}

void loop()
{
}
```

**Comment by polwel** [comment]
Yeah, not arguing that division is much more expressive.

I agree, using a division instead should have minimal performance impact. I am going with that one.

**Comment by Pharap** [comment]
I'm going to keep the issue open to remind me to review this anyway.

It's possible that the compiler won't properly optimise my current division implementation,
in which case I'll either look into adding a bit shift operator or finding a way to make the compiler optimise it.

I haven't had much chance to get through my issue backlog because I have many other projects on the go and I spend a lot of my spare time helping out at the Pokitto and Arduboy forums.

**Comment by rglory** [comment]
I tried to implement log2fix on Attiny402 with *= 2 and /= 2 and then replaced them with shifts. It reduces code size by 112 bytes which is very significant for 4K total. So no compiler (I am using gcc-avr 7.3.0) did not optimize properly and frankly I do not see how it could as you do not provide specialization for division by integer. So it uses division fixed/fixed type and that requires using bigger data type for intermediate result.
