### ISSUE TITLE
Add support for postincrement and postdecrement

### ISSUE THREAD

**Issue by miracoli** [Pharap/FixedPointsArduino#68]
I would not recommend anyone to use them, but for the sake of completeness...

**Comment by Pharap** [comment]
Is there a genuinely good reason for provding postfix operators? I can't think of one offhand.

**Comment by miracoli** [comment]
I can't either, but as already written, this is more for the sake of completeness. As a user, i would expect the fixed point data type to give me the same possibilities as the integrated data types. Whether this can be used in a useful way or not should, in my opinion, also be the decision of the user himself. I would simply give him the possibility to do so.

**Comment by Pharap** [comment]
Trying to provide capabilities similar to the integral/arithmetic types is a fair point.

Thinking back, I think the only reason I provided the prefix versions in the first place was because the floating point types support them.

Chances are they won't get used anyway since it seems they don't get used with the floating point types very often.
